/*
 * OncoKB APIs
 * OncoKB, a comprehensive and curated precision oncology knowledge base, offers oncologists detailed, evidence-based information about individual somatic mutations and structural alterations present in patient tumors with the goal of supporting optimal treatment decisions.
 *
 * OpenAPI spec version: v1.0.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.oncokb.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * LicenseAgreement
 */


public class LicenseAgreement {
  @SerializedName("acceptanceDate")
  private OffsetDateTime acceptanceDate = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("version")
  private String version = null;

  public LicenseAgreement acceptanceDate(OffsetDateTime acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
    return this;
  }

   /**
   * Get acceptanceDate
   * @return acceptanceDate
  **/
  @Schema(description = "")
  public OffsetDateTime getAcceptanceDate() {
    return acceptanceDate;
  }

  public void setAcceptanceDate(OffsetDateTime acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
  }

  public LicenseAgreement name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public LicenseAgreement version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LicenseAgreement licenseAgreement = (LicenseAgreement) o;
    return Objects.equals(this.acceptanceDate, licenseAgreement.acceptanceDate) &&
        Objects.equals(this.name, licenseAgreement.name) &&
        Objects.equals(this.version, licenseAgreement.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptanceDate, name, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LicenseAgreement {\n");
    
    sb.append("    acceptanceDate: ").append(toIndentedString(acceptanceDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
