/*
 * OncoKB APIs
 * OncoKB, a comprehensive and curated precision oncology knowledge base, offers oncologists detailed, evidence-based information about individual somatic mutations and structural alterations present in patient tumors with the goal of supporting optimal treatment decisions.
 *
 * OpenAPI spec version: v1.0.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.oncokb.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * UserOverviewUsage
 */


public class UserOverviewUsage {
  @SerializedName("endpoint")
  private String endpoint = null;

  @SerializedName("maxUsage")
  private Integer maxUsage = null;

  @SerializedName("noPrivateEndpoint")
  private String noPrivateEndpoint = null;

  @SerializedName("noPrivateMaxUsage")
  private Integer noPrivateMaxUsage = null;

  @SerializedName("totalUsage")
  private Integer totalUsage = null;

  @SerializedName("userEmail")
  private String userEmail = null;

  @SerializedName("userId")
  private String userId = null;

  public UserOverviewUsage endpoint(String endpoint) {
    this.endpoint = endpoint;
    return this;
  }

   /**
   * Get endpoint
   * @return endpoint
  **/
  @Schema(description = "")
  public String getEndpoint() {
    return endpoint;
  }

  public void setEndpoint(String endpoint) {
    this.endpoint = endpoint;
  }

  public UserOverviewUsage maxUsage(Integer maxUsage) {
    this.maxUsage = maxUsage;
    return this;
  }

   /**
   * Get maxUsage
   * @return maxUsage
  **/
  @Schema(description = "")
  public Integer getMaxUsage() {
    return maxUsage;
  }

  public void setMaxUsage(Integer maxUsage) {
    this.maxUsage = maxUsage;
  }

  public UserOverviewUsage noPrivateEndpoint(String noPrivateEndpoint) {
    this.noPrivateEndpoint = noPrivateEndpoint;
    return this;
  }

   /**
   * Get noPrivateEndpoint
   * @return noPrivateEndpoint
  **/
  @Schema(description = "")
  public String getNoPrivateEndpoint() {
    return noPrivateEndpoint;
  }

  public void setNoPrivateEndpoint(String noPrivateEndpoint) {
    this.noPrivateEndpoint = noPrivateEndpoint;
  }

  public UserOverviewUsage noPrivateMaxUsage(Integer noPrivateMaxUsage) {
    this.noPrivateMaxUsage = noPrivateMaxUsage;
    return this;
  }

   /**
   * Get noPrivateMaxUsage
   * @return noPrivateMaxUsage
  **/
  @Schema(description = "")
  public Integer getNoPrivateMaxUsage() {
    return noPrivateMaxUsage;
  }

  public void setNoPrivateMaxUsage(Integer noPrivateMaxUsage) {
    this.noPrivateMaxUsage = noPrivateMaxUsage;
  }

  public UserOverviewUsage totalUsage(Integer totalUsage) {
    this.totalUsage = totalUsage;
    return this;
  }

   /**
   * Get totalUsage
   * @return totalUsage
  **/
  @Schema(description = "")
  public Integer getTotalUsage() {
    return totalUsage;
  }

  public void setTotalUsage(Integer totalUsage) {
    this.totalUsage = totalUsage;
  }

  public UserOverviewUsage userEmail(String userEmail) {
    this.userEmail = userEmail;
    return this;
  }

   /**
   * Get userEmail
   * @return userEmail
  **/
  @Schema(description = "")
  public String getUserEmail() {
    return userEmail;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public UserOverviewUsage userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @Schema(description = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserOverviewUsage userOverviewUsage = (UserOverviewUsage) o;
    return Objects.equals(this.endpoint, userOverviewUsage.endpoint) &&
        Objects.equals(this.maxUsage, userOverviewUsage.maxUsage) &&
        Objects.equals(this.noPrivateEndpoint, userOverviewUsage.noPrivateEndpoint) &&
        Objects.equals(this.noPrivateMaxUsage, userOverviewUsage.noPrivateMaxUsage) &&
        Objects.equals(this.totalUsage, userOverviewUsage.totalUsage) &&
        Objects.equals(this.userEmail, userOverviewUsage.userEmail) &&
        Objects.equals(this.userId, userOverviewUsage.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpoint, maxUsage, noPrivateEndpoint, noPrivateMaxUsage, totalUsage, userEmail, userId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserOverviewUsage {\n");
    
    sb.append("    endpoint: ").append(toIndentedString(endpoint)).append("\n");
    sb.append("    maxUsage: ").append(toIndentedString(maxUsage)).append("\n");
    sb.append("    noPrivateEndpoint: ").append(toIndentedString(noPrivateEndpoint)).append("\n");
    sb.append("    noPrivateMaxUsage: ").append(toIndentedString(noPrivateMaxUsage)).append("\n");
    sb.append("    totalUsage: ").append(toIndentedString(totalUsage)).append("\n");
    sb.append("    userEmail: ").append(toIndentedString(userEmail)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
