/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.oncokb.oncokb_curation.client.IntegerFilter;
import org.oncokb.oncokb_curation.client.LongFilter;
import org.oncokb.oncokb_curation.client.StringFilter;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AlterationCriteria
 */
public class AlterationCriteriaTest {
    private final AlterationCriteria model = new AlterationCriteria();

    /**
     * Model tests for AlterationCriteria
     */
    @Test
    public void testAlterationCriteria() {
        // TODO: test AlterationCriteria
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'alteration'
     */
    @Test
    public void alterationTest() {
        // TODO: test alteration
    }

    /**
     * Test the property 'proteinStart'
     */
    @Test
    public void proteinStartTest() {
        // TODO: test proteinStart
    }

    /**
     * Test the property 'proteinEnd'
     */
    @Test
    public void proteinEndTest() {
        // TODO: test proteinEnd
    }

    /**
     * Test the property 'refResidues'
     */
    @Test
    public void refResiduesTest() {
        // TODO: test refResidues
    }

    /**
     * Test the property 'variantResidues'
     */
    @Test
    public void variantResiduesTest() {
        // TODO: test variantResidues
    }

    /**
     * Test the property 'biomarkerAssociationId'
     */
    @Test
    public void biomarkerAssociationIdTest() {
        // TODO: test biomarkerAssociationId
    }

    /**
     * Test the property 'referenceGenomesId'
     */
    @Test
    public void referenceGenomesIdTest() {
        // TODO: test referenceGenomesId
    }

    /**
     * Test the property 'geneId'
     */
    @Test
    public void geneIdTest() {
        // TODO: test geneId
    }

    /**
     * Test the property 'consequenceId'
     */
    @Test
    public void consequenceIdTest() {
        // TODO: test consequenceId
    }

    /**
     * Test the property 'distinct'
     */
    @Test
    public void distinctTest() {
        // TODO: test distinct
    }

}
