/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Article
 */
public class ArticleTest {
    private final Article model = new Article();

    /**
     * Model tests for Article
     */
    @Test
    public void testArticle() {
        // TODO: test Article
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'pmid'
     */
    @Test
    public void pmidTest() {
        // TODO: test pmid
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'journal'
     */
    @Test
    public void journalTest() {
        // TODO: test journal
    }

    /**
     * Test the property 'pubDate'
     */
    @Test
    public void pubDateTest() {
        // TODO: test pubDate
    }

    /**
     * Test the property 'volume'
     */
    @Test
    public void volumeTest() {
        // TODO: test volume
    }

    /**
     * Test the property 'issue'
     */
    @Test
    public void issueTest() {
        // TODO: test issue
    }

    /**
     * Test the property 'pages'
     */
    @Test
    public void pagesTest() {
        // TODO: test pages
    }

    /**
     * Test the property 'authors'
     */
    @Test
    public void authorsTest() {
        // TODO: test authors
    }

}
