/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.oncokb.oncokb_curation.client.IntegerFilter;
import org.oncokb.oncokb_curation.client.LongFilter;
import org.oncokb.oncokb_curation.client.StringFilter;
import org.oncokb.oncokb_curation.client.TumorFormFilter;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CancerTypeCriteria
 */
public class CancerTypeCriteriaTest {
    private final CancerTypeCriteria model = new CancerTypeCriteria();

    /**
     * Model tests for CancerTypeCriteria
     */
    @Test
    public void testCancerTypeCriteria() {
        // TODO: test CancerTypeCriteria
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'mainType'
     */
    @Test
    public void mainTypeTest() {
        // TODO: test mainType
    }

    /**
     * Test the property 'subtype'
     */
    @Test
    public void subtypeTest() {
        // TODO: test subtype
    }

    /**
     * Test the property 'tissue'
     */
    @Test
    public void tissueTest() {
        // TODO: test tissue
    }

    /**
     * Test the property 'tumorForm'
     */
    @Test
    public void tumorFormTest() {
        // TODO: test tumorForm
    }

    /**
     * Test the property 'childrenId'
     */
    @Test
    public void childrenIdTest() {
        // TODO: test childrenId
    }

    /**
     * Test the property 'biomarkerAssociationId'
     */
    @Test
    public void biomarkerAssociationIdTest() {
        // TODO: test biomarkerAssociationId
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'distinct'
     */
    @Test
    public void distinctTest() {
        // TODO: test distinct
    }

}
