/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.oncokb.oncokb_curation.client.BiomarkerAssociation;
import org.oncokb.oncokb_curation.client.DrugBrand;
import org.oncokb.oncokb_curation.client.DrugSynonym;
import org.oncokb.oncokb_curation.client.FdaDrug;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Drug
 */
public class DrugTest {
    private final Drug model = new Drug();

    /**
     * Model tests for Drug
     */
    @Test
    public void testDrug() {
        // TODO: test Drug
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'semanticType'
     */
    @Test
    public void semanticTypeTest() {
        // TODO: test semanticType
    }

    /**
     * Test the property 'fdaDrug'
     */
    @Test
    public void fdaDrugTest() {
        // TODO: test fdaDrug
    }

    /**
     * Test the property 'synonyms'
     */
    @Test
    public void synonymsTest() {
        // TODO: test synonyms
    }

    /**
     * Test the property 'brands'
     */
    @Test
    public void brandsTest() {
        // TODO: test brands
    }

    /**
     * Test the property 'biomarkerAssociations'
     */
    @Test
    public void biomarkerAssociationsTest() {
        // TODO: test biomarkerAssociations
    }

}
