/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import org.oncokb.oncokb_curation.ApiException;
import org.oncokb.oncokb_curation.client.FdaSubmissionType;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FdaSubmissionTypeResourceApi
 */
@Ignore
public class FdaSubmissionTypeResourceApiTest {

    private final FdaSubmissionTypeResourceApi api = new FdaSubmissionTypeResourceApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFdaSubmissionTypeTest() throws ApiException {
        FdaSubmissionType fdaSubmissionType = null;
                FdaSubmissionType response = api.createFdaSubmissionType(fdaSubmissionType);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFdaSubmissionTypeTest() throws ApiException {
        Long id = null;
                api.deleteFdaSubmissionType(id);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllFdaSubmissionTypesTest() throws ApiException {
                List<FdaSubmissionType> response = api.getAllFdaSubmissionTypes();
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFdaSubmissionTypeTest() throws ApiException {
        Long id = null;
                FdaSubmissionType response = api.getFdaSubmissionType(id);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partialUpdateFdaSubmissionTypeTest() throws ApiException {
        Long id = null;
        FdaSubmissionType fdaSubmissionType = null;
                FdaSubmissionType response = api.partialUpdateFdaSubmissionType(id, fdaSubmissionType);
        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFdaSubmissionTypeTest() throws ApiException {
        Long id = null;
        FdaSubmissionType fdaSubmissionType = null;
                FdaSubmissionType response = api.updateFdaSubmissionType(id, fdaSubmissionType);
        // TODO: test validations
    }
    
}
