/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Gene
 */
public class GeneTest {
    private final Gene model = new Gene();

    /**
     * Model tests for Gene
     */
    @Test
    public void testGene() {
        // TODO: test Gene
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'entrezGeneId'
     */
    @Test
    public void entrezGeneIdTest() {
        // TODO: test entrezGeneId
    }

    /**
     * Test the property 'hugoSymbol'
     */
    @Test
    public void hugoSymbolTest() {
        // TODO: test hugoSymbol
    }

}
