/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LongFilter
 */
public class LongFilterTest {
    private final LongFilter model = new LongFilter();

    /**
     * Model tests for LongFilter
     */
    @Test
    public void testLongFilter() {
        // TODO: test LongFilter
    }

    /**
     * Test the property 'equals'
     */
    @Test
    public void equalsTest() {
        // TODO: test equals
    }

    /**
     * Test the property 'notEquals'
     */
    @Test
    public void notEqualsTest() {
        // TODO: test notEquals
    }

    /**
     * Test the property 'specified'
     */
    @Test
    public void specifiedTest() {
        // TODO: test specified
    }

    /**
     * Test the property 'in'
     */
    @Test
    public void inTest() {
        // TODO: test in
    }

    /**
     * Test the property 'notIn'
     */
    @Test
    public void notInTest() {
        // TODO: test notIn
    }

    /**
     * Test the property 'greaterThan'
     */
    @Test
    public void greaterThanTest() {
        // TODO: test greaterThan
    }

    /**
     * Test the property 'lessThan'
     */
    @Test
    public void lessThanTest() {
        // TODO: test lessThan
    }

    /**
     * Test the property 'greaterThanOrEqual'
     */
    @Test
    public void greaterThanOrEqualTest() {
        // TODO: test greaterThanOrEqual
    }

    /**
     * Test the property 'lessThanOrEqual'
     */
    @Test
    public void lessThanOrEqualTest() {
        // TODO: test lessThanOrEqual
    }

}
