/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.oncokb.oncokb_curation.client.Alteration;
import org.oncokb.oncokb_curation.client.Article;
import org.oncokb.oncokb_curation.client.CompanionDiagnosticDevice;
import org.oncokb.oncokb_curation.client.Drug;
import org.oncokb.oncokb_curation.client.FdaSubmission;
import org.oncokb.oncokb_curation.client.Gene;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SearchResultDTO
 */
public class SearchResultDTOTest {
    private final SearchResultDTO model = new SearchResultDTO();

    /**
     * Model tests for SearchResultDTO
     */
    @Test
    public void testSearchResultDTO() {
        // TODO: test SearchResultDTO
    }

    /**
     * Test the property 'fdaSubmissions'
     */
    @Test
    public void fdaSubmissionsTest() {
        // TODO: test fdaSubmissions
    }

    /**
     * Test the property 'companionDiagnosticDevices'
     */
    @Test
    public void companionDiagnosticDevicesTest() {
        // TODO: test companionDiagnosticDevices
    }

    /**
     * Test the property 'articles'
     */
    @Test
    public void articlesTest() {
        // TODO: test articles
    }

    /**
     * Test the property 'drugs'
     */
    @Test
    public void drugsTest() {
        // TODO: test drugs
    }

    /**
     * Test the property 'genes'
     */
    @Test
    public void genesTest() {
        // TODO: test genes
    }

    /**
     * Test the property 'alterations'
     */
    @Test
    public void alterationsTest() {
        // TODO: test alterations
    }

}
