/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_curation.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.oncokb.oncokb_curation.client.TranscriptPairVM;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TranscriptComparisonVM
 */
public class TranscriptComparisonVMTest {
    private final TranscriptComparisonVM model = new TranscriptComparisonVM();

    /**
     * Model tests for TranscriptComparisonVM
     */
    @Test
    public void testTranscriptComparisonVM() {
        // TODO: test TranscriptComparisonVM
    }

    /**
     * Test the property 'align'
     */
    @Test
    public void alignTest() {
        // TODO: test align
    }

    /**
     * Test the property 'transcriptA'
     */
    @Test
    public void transcriptATest() {
        // TODO: test transcriptA
    }

    /**
     * Test the property 'transcriptB'
     */
    @Test
    public void transcriptBTest() {
        // TODO: test transcriptB
    }

}
