/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.4.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AnnotateMutationByHGVSgQuery
 */
public class AnnotateMutationByHGVSgQueryTest {
    private final AnnotateMutationByHGVSgQuery model = new AnnotateMutationByHGVSgQuery();

    /**
     * Model tests for AnnotateMutationByHGVSgQuery
     */
    @Test
    public void testAnnotateMutationByHGVSgQuery() {
        // TODO: test AnnotateMutationByHGVSgQuery
    }

    /**
     * Test the property 'evidenceTypes'
     */
    @Test
    public void evidenceTypesTest() {
        // TODO: test evidenceTypes
    }

    /**
     * Test the property 'hgvsg'
     */
    @Test
    public void hgvsgTest() {
        // TODO: test hgvsg
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'referenceGenome'
     */
    @Test
    public void referenceGenomeTest() {
        // TODO: test referenceGenome
    }

    /**
     * Test the property 'tumorType'
     */
    @Test
    public void tumorTypeTest() {
        // TODO: test tumorType
    }

}
