/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.4.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CancerTypesQuery
 */
public class CancerTypesQueryTest {
    private final CancerTypesQuery model = new CancerTypesQuery();

    /**
     * Model tests for CancerTypesQuery
     */
    @Test
    public void testCancerTypesQuery() {
        // TODO: test CancerTypesQuery
    }

    /**
     * Test the property 'cancerTypes'
     */
    @Test
    public void cancerTypesTest() {
        // TODO: test cancerTypes
    }

}
