/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.2.2
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import org.oncokb.ApiException;
import org.oncokb.client.Alteration;
import org.oncokb.client.Gene;
import org.oncokb.client.GeneEvidence;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenesApi
 */
@Ignore
public class GenesApiTest {

    private final GenesApi api = new GenesApi();

    
    /**
     * genesEntrezGeneIdEvidencesGet
     *
     * Get list of evidences for specific gene.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genesEntrezGeneIdEvidencesGetUsingGETTest() throws ApiException {
        Integer entrezGeneId = null;
        String evidenceTypes = null;
                List<GeneEvidence> response = api.genesEntrezGeneIdEvidencesGetUsingGET(entrezGeneId, evidenceTypes);
        // TODO: test validations
    }
    
    /**
     * genesEntrezGeneIdGet
     *
     * Get specific gene information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genesEntrezGeneIdGetUsingGETTest() throws ApiException {
        Integer entrezGeneId = null;
        String fields = null;
                Gene response = api.genesEntrezGeneIdGetUsingGET(entrezGeneId, fields);
        // TODO: test validations
    }
    
    /**
     * genesEntrezGeneIdVariantsGet
     *
     * Get list of variants for specific gene.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genesEntrezGeneIdVariantsGetUsingGETTest() throws ApiException {
        Integer entrezGeneId = null;
        String fields = null;
                List<Alteration> response = api.genesEntrezGeneIdVariantsGetUsingGET(entrezGeneId, fields);
        // TODO: test validations
    }
    
    /**
     * genesGet
     *
     * Get list of currently curated genes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genesGetUsingGETTest() throws ApiException {
        String fields = null;
                List<Gene> response = api.genesGetUsingGET(fields);
        // TODO: test validations
    }
    
    /**
     * genesLookupGet
     *
     * Search gene.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void genesLookupGetUsingGETTest() throws ApiException {
        String hugoSymbol = null;
        Integer entrezGeneId = null;
        String query = null;
        String fields = null;
                List<Gene> response = api.genesLookupGetUsingGET(hugoSymbol, entrezGeneId, query, fields);
        // TODO: test validations
    }
    
}
