/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.4.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.oncokb.client.Geneset;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Gene
 */
public class GeneTest {
    private final Gene model = new Gene();

    /**
     * Model tests for Gene
     */
    @Test
    public void testGene() {
        // TODO: test Gene
    }

    /**
     * Test the property 'entrezGeneId'
     */
    @Test
    public void entrezGeneIdTest() {
        // TODO: test entrezGeneId
    }

    /**
     * Test the property 'geneAliases'
     */
    @Test
    public void geneAliasesTest() {
        // TODO: test geneAliases
    }

    /**
     * Test the property 'genesets'
     */
    @Test
    public void genesetsTest() {
        // TODO: test genesets
    }

    /**
     * Test the property 'grch37Isoform'
     */
    @Test
    public void grch37IsoformTest() {
        // TODO: test grch37Isoform
    }

    /**
     * Test the property 'grch37RefSeq'
     */
    @Test
    public void grch37RefSeqTest() {
        // TODO: test grch37RefSeq
    }

    /**
     * Test the property 'grch38Isoform'
     */
    @Test
    public void grch38IsoformTest() {
        // TODO: test grch38Isoform
    }

    /**
     * Test the property 'grch38RefSeq'
     */
    @Test
    public void grch38RefSeqTest() {
        // TODO: test grch38RefSeq
    }

    /**
     * Test the property 'hugoSymbol'
     */
    @Test
    public void hugoSymbolTest() {
        // TODO: test hugoSymbol
    }

    /**
     * Test the property 'oncogene'
     */
    @Test
    public void oncogeneTest() {
        // TODO: test oncogene
    }

    /**
     * Test the property 'tsg'
     */
    @Test
    public void tsgTest() {
        // TODO: test tsg
    }

}
