/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.4.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.oncokb.client.ArticleAbstract;
import org.oncokb.client.Drug;
import org.oncokb.client.TumorType;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for IndicatorQueryTreatment
 */
public class IndicatorQueryTreatmentTest {
    private final IndicatorQueryTreatment model = new IndicatorQueryTreatment();

    /**
     * Model tests for IndicatorQueryTreatment
     */
    @Test
    public void testIndicatorQueryTreatment() {
        // TODO: test IndicatorQueryTreatment
    }

    /**
     * Test the property 'abstracts'
     */
    @Test
    public void abstractsTest() {
        // TODO: test abstracts
    }

    /**
     * Test the property 'alterations'
     */
    @Test
    public void alterationsTest() {
        // TODO: test alterations
    }

    /**
     * Test the property 'approvedIndications'
     */
    @Test
    public void approvedIndicationsTest() {
        // TODO: test approvedIndications
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'drugs'
     */
    @Test
    public void drugsTest() {
        // TODO: test drugs
    }

    /**
     * Test the property 'fdaLevel'
     */
    @Test
    public void fdaLevelTest() {
        // TODO: test fdaLevel
    }

    /**
     * Test the property 'level'
     */
    @Test
    public void levelTest() {
        // TODO: test level
    }

    /**
     * Test the property 'levelAssociatedCancerType'
     */
    @Test
    public void levelAssociatedCancerTypeTest() {
        // TODO: test levelAssociatedCancerType
    }

    /**
     * Test the property 'levelExcludedCancerTypes'
     */
    @Test
    public void levelExcludedCancerTypesTest() {
        // TODO: test levelExcludedCancerTypes
    }

    /**
     * Test the property 'pmids'
     */
    @Test
    public void pmidsTest() {
        // TODO: test pmids
    }

}
