/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.2.2
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.oncokb.client.InfoLevel;
import org.oncokb.client.Version;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for OncoKBInfo
 */
public class OncoKBInfoTest {
    private final OncoKBInfo model = new OncoKBInfo();

    /**
     * Model tests for OncoKBInfo
     */
    @Test
    public void testOncoKBInfo() {
        // TODO: test OncoKBInfo
    }

    /**
     * Test the property 'apiVersion'
     */
    @Test
    public void apiVersionTest() {
        // TODO: test apiVersion
    }

    /**
     * Test the property 'dataVersion'
     */
    @Test
    public void dataVersionTest() {
        // TODO: test dataVersion
    }

    /**
     * Test the property 'levels'
     */
    @Test
    public void levelsTest() {
        // TODO: test levels
    }

    /**
     * Test the property 'ncitVersion'
     */
    @Test
    public void ncitVersionTest() {
        // TODO: test ncitVersion
    }

    /**
     * Test the property 'oncoTreeVersion'
     */
    @Test
    public void oncoTreeVersionTest() {
        // TODO: test oncoTreeVersion
    }

    /**
     * Test the property 'publicInstance'
     */
    @Test
    public void publicInstanceTest() {
        // TODO: test publicInstance
    }

}
