/*
 * OncoKB Private APIs
 * These endpoints are for private use only.
 *
 * The version of the OpenAPI document: v1.2.2
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for VariantSearchQuery
 */
public class VariantSearchQueryTest {
    private final VariantSearchQuery model = new VariantSearchQuery();

    /**
     * Model tests for VariantSearchQuery
     */
    @Test
    public void testVariantSearchQuery() {
        // TODO: test VariantSearchQuery
    }

    /**
     * Test the property 'consequence'
     */
    @Test
    public void consequenceTest() {
        // TODO: test consequence
    }

    /**
     * Test the property 'entrezGeneId'
     */
    @Test
    public void entrezGeneIdTest() {
        // TODO: test entrezGeneId
    }

    /**
     * Test the property 'hgvs'
     */
    @Test
    public void hgvsTest() {
        // TODO: test hgvs
    }

    /**
     * Test the property 'hugoSymbol'
     */
    @Test
    public void hugoSymbolTest() {
        // TODO: test hugoSymbol
    }

    /**
     * Test the property 'proteinEnd'
     */
    @Test
    public void proteinEndTest() {
        // TODO: test proteinEnd
    }

    /**
     * Test the property 'proteinStart'
     */
    @Test
    public void proteinStartTest() {
        // TODO: test proteinStart
    }

    /**
     * Test the property 'referenceGenome'
     */
    @Test
    public void referenceGenomeTest() {
        // TODO: test referenceGenome
    }

    /**
     * Test the property 'variant'
     */
    @Test
    public void variantTest() {
        // TODO: test variant
    }

    /**
     * Test the property 'variantType'
     */
    @Test
    public void variantTypeTest() {
        // TODO: test variantType
    }

}
