/*
 * OncoKB APIs
 * OncoKB, a comprehensive and curated precision oncology knowledge base, offers oncologists detailed, evidence-based information about individual somatic mutations and structural alterations present in patient tumors with the goal of supporting optimal treatment decisions.
 *
 * OpenAPI spec version: v1.2.2
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.oncokb.client;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.oncokb.client.Citations;

/**
 * MutationEffectResp
 */

public class MutationEffectResp {
  @SerializedName("citations")
  private Citations citations = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("knownEffect")
  private String knownEffect = null;

  public MutationEffectResp citations(Citations citations) {
    this.citations = citations;
    return this;
  }

   /**
   * Get citations
   * @return citations
  **/
  @ApiModelProperty(value = "")
  public Citations getCitations() {
    return citations;
  }

  public void setCitations(Citations citations) {
    this.citations = citations;
  }

  public MutationEffectResp description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public MutationEffectResp knownEffect(String knownEffect) {
    this.knownEffect = knownEffect;
    return this;
  }

   /**
   * Get knownEffect
   * @return knownEffect
  **/
  @ApiModelProperty(value = "")
  public String getKnownEffect() {
    return knownEffect;
  }

  public void setKnownEffect(String knownEffect) {
    this.knownEffect = knownEffect;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MutationEffectResp mutationEffectResp = (MutationEffectResp) o;
    return Objects.equals(this.citations, mutationEffectResp.citations) &&
        Objects.equals(this.description, mutationEffectResp.description) &&
        Objects.equals(this.knownEffect, mutationEffectResp.knownEffect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(citations, description, knownEffect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MutationEffectResp {\n");
    
    sb.append("    citations: ").append(toIndentedString(citations)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    knownEffect: ").append(toIndentedString(knownEffect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

