/*
 * OncoKB APIs for Premium Users
 * These endpoints are designed for premium users. Please contact OncoKB team(contact@oncokb.org) if you want to be upgraded.
 *
 * OpenAPI spec version: v1.0.0
 * Contact: contact@oncokb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.oncokb.client;

import org.oncokb.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LevelsApi
 */
@Ignore
public class LevelsApiTest {

    private final LevelsApi api = new LevelsApi();

    
    /**
     * levelsGet
     *
     * Get all levels.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void levelsGetUsingGET1Test() throws ApiException {
        Object response = api.levelsGetUsingGET1();

        // TODO: test validations
    }
    
    /**
     * levelsResistanceGet
     *
     * Get all resistance levels.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void levelsResistanceGetUsingGET1Test() throws ApiException {
        Object response = api.levelsResistanceGetUsingGET1();

        // TODO: test validations
    }
    
    /**
     * levelsSensitiveGet
     *
     * Get all sensitive levels.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void levelsSensitiveGetUsingGET1Test() throws ApiException {
        Object response = api.levelsSensitiveGetUsingGET1();

        // TODO: test validations
    }
    
}
