/*
 * oncokb-transcript API
 * oncokb-transcript API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.oncokb.oncokb_transcript.client;

import org.oncokb.oncokb_transcript.ApiException;
import org.oncokb.oncokb_transcript.client.Drug;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DrugResourceApi
 */
@Ignore
public class DrugResourceApiTest {

    private final DrugResourceApi api = new DrugResourceApi();

    /**
     * createDrug
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createDrugUsingPOSTTest() throws ApiException {
        Drug body = null;
        Drug response = api.createDrugUsingPOST(body);

        // TODO: test validations
    }
    /**
     * deleteDrug
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteDrugUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteDrugUsingDELETE(id);

        // TODO: test validations
    }
    /**
     * findDrugByCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findDrugByCodeUsingGETTest() throws ApiException {
        String code = null;
        Drug response = api.findDrugByCodeUsingGET(code);

        // TODO: test validations
    }
    /**
     * findDrugs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findDrugsUsingGETTest() throws ApiException {
        String query = null;
        List<Drug> response = api.findDrugsUsingGET(query);

        // TODO: test validations
    }
    /**
     * getAllDrugs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllDrugsUsingGETTest() throws ApiException {
        List<Drug> response = api.getAllDrugsUsingGET();

        // TODO: test validations
    }
    /**
     * getDrug
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDrugUsingGETTest() throws ApiException {
        Long id = null;
        Drug response = api.getDrugUsingGET(id);

        // TODO: test validations
    }
    /**
     * partialUpdateDrug
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void partialUpdateDrugUsingPATCHTest() throws ApiException {
        Long id = null;
        Drug body = null;
        Drug response = api.partialUpdateDrugUsingPATCH(id, body);

        // TODO: test validations
    }
    /**
     * updateDrug
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateDrugUsingPUTTest() throws ApiException {
        Long id = null;
        Drug body = null;
        Drug response = api.updateDrugUsingPUT(id, body);

        // TODO: test validations
    }
}
