/*
 * oncokb-transcript API
 * oncokb-transcript API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.oncokb.oncokb_transcript.client;

import org.oncokb.oncokb_transcript.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PipelineControllerApi
 */
@Ignore
public class PipelineControllerApiTest {

    private final PipelineControllerApi api = new PipelineControllerApi();

    /**
     * updateNcit
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateNcitUsingPOSTTest() throws ApiException {
        api.updateNcitUsingPOST();

        // TODO: test validations
    }
    /**
     * updatePortalGene
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updatePortalGeneUsingPOSTTest() throws ApiException {
        api.updatePortalGeneUsingPOST();

        // TODO: test validations
    }
}
