/*
 * oncokb-transcript API
 * oncokb-transcript API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.oncokb.oncokb_transcript.client;

import org.oncokb.oncokb_transcript.client.Sequence;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for SequenceControllerApi
 */
@Ignore
public class SequenceControllerApiTest {

    private final SequenceControllerApi api = new SequenceControllerApi();

    /**
     * findSequencesByUsageSource
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void findSequencesByUsageSourceUsingGETTest() throws Exception {
        String referenceGenome = null;
        String usageSource = null;
        String hugoSymbol = null;
        List<Sequence> response = api.findSequencesByUsageSourceUsingGET(referenceGenome, usageSource, hugoSymbol);

        // TODO: test validations
    }
}
