/*
 * oncokb-transcript API
 * oncokb-transcript API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.oncokb.oncokb_transcript.client;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TranscriptSuggestionVM
 */
public class TranscriptSuggestionVMTest {
    private final TranscriptSuggestionVM model = new TranscriptSuggestionVM();

    /**
     * Model tests for TranscriptSuggestionVM
     */
    @Test
    public void testTranscriptSuggestionVM() {
        // TODO: test TranscriptSuggestionVM
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'referenceGenome'
     */
    @Test
    public void referenceGenomeTest() {
        // TODO: test referenceGenome
    }

    /**
     * Test the property 'suggestions'
     */
    @Test
    public void suggestionsTest() {
        // TODO: test suggestions
    }

}
